name: bb
favicon: null
layout_spectrum: 1
typography_spectrum: 0.68038
title: Blankhaus Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1d1d1b'
    - '#d5d5d5'
    - '#585856'
    - '#858585'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
