name: bb
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5105516058392823
title: Blankhaus Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.41342055751010776
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 0.42395183769986033
purpose: []
